services:
  app:
    build:
      context: .
      args:
        GO_VERSION: 1.24.2
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
